### PR TITLE
[schema]: Change state table name with suffix STATE_TABLE

### PR DESCRIPTION
**Pull request by stcheng**
In the current schema, the state tabel names have conflicts with the
application table names. e.g. PORT_TABLE. It will cause issues when
one Orch class subscribes to two of these tables and uses the table
name to distinguish which table it is.

It is good to make distinctive names even if tables are in different
databases.

Signed-off-by: Shu0T1an ChenG <shuche@microsoft.com>

### CODE REVIEW

**Comment by qiluo-msft** [comment]
I believe
> uses the table name to distinguish which table it is.

is a bad design. However I agree this is a quick workaround.

**Comment by stcheng** [comment]
yes. the ideal solution is to use <db, table_name> pair to distinguish them

**Comment by prsunny** [comment]
Just a thought, you could identify by the attribute "state" right?

**Comment by qiluo-msft** [comment]
Solve the conflict?

**Comment by lguohan** [comment]
build failure

**Comment by lguohan** [comment]
what do you mean by "uses the table name to distinguish which table it is."? can we use other ways to distinguish which table it is?

**Pull request closed without merging**
