### PR TITLE
[schema] Class Based Forwarding

### PR DESCRIPTION
**Pull request by abanu-ms**
* Added table name for CBF NHGs

* Added table name for FC_TO_NHG_INDEX NHG maps

* Added DSCP_TO_FC_MAP and EXP_TO_FC_MAP tables

Signed-off-by: Alexandru Banu <v-albanu@microsoft.com>

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by abanu-ms** [comment]
> Could you add a link to a design doc?

Here's the PR for the HLD: https://github.com/Azure/SONiC/pull/796

**Review by kcudnik — APPROVED** [review]

**Comment by abanu-ms** [comment]
Can this be merged?

**Comment by TACappleman** [comment]
@kcudnik can this be merged please?

**Comment by kcudnik** [comment]
done

**Pull request merged**
