### PR TITLE
Splitting common library into two libraries

### PR DESCRIPTION
**Pull request by stcheng**
one with libnl
one without

### CODE REVIEW

**Comment by kcudnik** [comment]
What is purpose of that split?

**Comment by lguohan** [comment]
so that syncd does not need to depends on libnl

**Comment by lguohan** [comment]
ack

**Comment by stcheng** [comment]
Delayed for future evaluation.

**Comment by kcudnik** [comment]
ack

**Comment by stcheng** [comment]
close for now. leave it for future discussion.

**Pull request closed without merging**
