### PR TITLE
[IpAddress]: add mcast scope on address and isFullMask method on prefix

### PR DESCRIPTION
**Pull request by tylerlinp**
1. add mcast scope on IpAddress class
2. add isFullMask method on IpPrefix class

### CODE REVIEW

**Comment by kcudnik** [comment]
add some unittests for those changes ?

**Comment by tylerlinp** [comment]
Yes, in sonic-swss PR:
https://github.com/Azure/sonic-swss/pull/943

**Comment by lguohan** [comment]
unit test code should be in this repo.

**Comment by tylerlinp** [comment]
OK. Unit test code has been added.

**Pull request merged**
