### PR TITLE
Fix bug: RedisTransactioner pops empty container, mistaken copy constructor usage

### PR DESCRIPTION
**Pull request by qiluo-msft**
Include several fixes and refactors:
- Simply refactor DBConnector hgetall()
- Fix RedisTransactioner: handle empty deque
- Move complex class constructor as explicit, and fix several mistaken copy constructor usage

### CODE REVIEW

**Comment by qiluo-msft** [comment]
Retest this please

**Review by shi-su — APPROVED** [review]

**Comment by lguohan** [comment]
do you want squash merge or rebase merge?

**Comment by qiluo-msft** [comment]
@lguohan, I will squash merge by default. What is your preference on this PR?

**Comment by lguohan** [comment]
it seems the commits are well organized, it is up-to your decision. my general preference is that if the commits are organized, then we do not have to squash and merge.

**Pull request merged**
