### PR TITLE
[ci]: Change diff coverage threshold to 80% 

### PR DESCRIPTION
**Pull request by liuh-80**
Change diff coverage threshold to 80%

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Review by kcudnik — APPROVED** [review]

**Comment by liuh-80** [comment]
Some UT seems not stable, will run test again and merge after all UT passed:

2022-06-14T05:11:26.0157995Z test_NeighborAddRemoveIpv6LinkLocal failed (1 runs remaining out of 2).
2022-06-14T05:11:26.0158614Z 	<class 'AssertionError'>
2022-06-14T05:11:26.0158782Z 	assert 2 == 4
2022-06-14T05:11:26.0158998Z   -2
2022-06-14T05:11:26.0159130Z   +4
2022-06-14T05:11:26.0159461Z 	[<TracebackEntry /agent/_work/1/s/sonic-swss/tests/test_ipv6_link_local.py:63>]


2022-06-14T05:11:26.0228705Z test_VlanIncrementalConfig failed (1 runs remaining out of 2).
2022-06-14T05:11:26.0229119Z 	<class 'AssertionError'>
2022-06-14T05:11:26.0229260Z 	
2022-06-14T05:11:26.0229693Z 	[<TracebackEntry /agent/_work/1/s/sonic-swss/tests/test_vlan.py:122>, <TracebackEntry /agent/_work/1/s/sonic-swss/tests/dvslib/dvs_vlan.py:53>]


2022-06-14T05:11:26.0251913Z test_MirrorSessionAddModifyAndDelete failed (1 runs remaining out of 2).
2022-06-14T05:11:26.0252214Z 	<class 'ValueError'>
2022-06-14T05:11:26.0252394Z 	filedescriptor out of range in select()
2022-06-14T05:11:26.0254601Z 	[<TracebackEntry /agent/_work/1/s/sonic-swss/tests/conftest.py:1794>, <TracebackEntry /agent/_work/1/s/sonic-swss/tests/conftest.py:1775>, <TracebackEntry /agent/_work/1/s/sonic-swss/tests/conftest.py:591>, <TracebackEntry /agent/_work/1/s/sonic-swss/tests/conftest.py:454>, <TracebackEntry /agent/_work/1/s/sonic-swss/tests/conftest.py:492>, <TracebackEntry /agent/_work/1/s/sonic-swss/tests/dvslib/dvs_common.py:51>, <TracebackEntry /agent/_work/1/s/sonic-swss/tests/conftest.py:474>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/models/containers.py:198>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/decorators.py:19>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/exec_api.py:169>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/client.py:422>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:137>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/api/client.py:416>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:94>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:66>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:51>, <TracebackEntry /usr/local/lib/python3.8/dist-packages/docker/utils/socket.py:31>]

**Comment by liuh-80** [comment]
Some UT are really not stable, this PR does not change anything and it failed, will retry again:

2022-06-16T08:35:01.7176724Z test_qos_map.py::TestDscpToTcMap::test_dscp_to_tc_map_applied_to_switch FAILED [ 75%]
2022-06-16T09:53:56.3609162Z test_NeighborAddRemoveIpv6LinkLocal failed (1 runs remaining out of 2).
2022-06-16T09:53:56.3712133Z test_dscp_to_tc_map_applied_to_switch failed (1 runs remaining out of 2).
2022-06-16T09:53:56.3785899Z test_system_warmreboot_neighbor_syncup failed (1 runs remaining out of 2).

**Comment by liuh-80** [comment]
2 test case failed, seems the set time issue been fixed. will try again

2022-06-23T00:51:18.8452810Z [  FAILED  ] LegacyFdbEntry.fdb_entry_get
2022-06-23T00:51:18.8453269Z [  FAILED  ] Legacy.switch_get

**Pull request merged**
