### PR TITLE
Add a ctor for IpPrefix to accept ip structure and mask

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Why I did this?

Need to construct a IpPrefix instance from ip structure and mask length.

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
Adding unit test case...

**Review by prsunny — APPROVED** [review]
lgtm

**Review by qiluo-msft — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Checker depending on https://github.com/Azure/sonic-swss-common/pull/596

**Review by keboliu — APPROVED** [review]

**Pull request merged**
