### PR TITLE
Clear the fvs vector before popping the message out of notification consumer queue.

### PR DESCRIPTION
**Pull request by mint570**
Also make op, data, fvs vector local to while loop where they are actually used in pops().

Co-authored-by: Ashish Singh [ashishksingh@google.com](mailto:ashishksingh@google.com)

### CODE REVIEW

**Comment by mint570** [comment]
@qiluo-msft

**Review by qiluo-msft — COMMENTED** [review]
LGTM

**Comment by mint570** [comment]
@kcudnik 
Can you please take a look?

**Review by kcudnik — APPROVED** [review]

**Comment by mint570** [comment]
@qiluo-msft 
Can this PR be merged now? Thanks.

**Pull request merged**
