### PR TITLE
[schema.h]: Add PLUGIN_TYPE

### PR DESCRIPTION
**Pull request by marian-pritsak**
This define will replace SAI_OBJECT_TYPE but in order
not to break build, it will be removed after the change in client
code.

### CODE REVIEW

**Comment by marian-pritsak** [comment]
@stcheng @lguohan Can you please merge?

**Comment by stcheng** [comment]
actually this name is not intuitive to me. maybe 'LUA_PLUGIN' prefix is better?
also could you move these two 'PLUGIN' lines together?

**Comment by marian-pritsak** [comment]
Done

**Comment by stcheng** [comment]
Later could you also update the `PLUGIN_TABLE` to `LUA_PLUGIN_TABLE`?

**Comment by lguohan** [comment]
is this still needed? any dependency? can i merge?

**Comment by marian-pritsak** [comment]
It's needed. It's part of renaming 'PFC WD' to 'FLEX_COUNTER'.

**Pull request merged**
