### PR TITLE
[nvgre] Added NVGRE tunnel related tables

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
Added NVGRE tunnel related tables

Signed-off-by: Vadym Hlushko <vadymh@nvidia.com>

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@@kperumalbfn could you please help to review?

**Comment by vadymhlushko-mlnx** [comment]
@kperumalbfn, kind reminder, could you please help to review this PR

**Review by kcudnik — APPROVED** [review]

**Review by kperumalbfn — APPROVED** [review]

**Comment by vadymhlushko-mlnx** [comment]
@kcudnik could you please merge?

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
