### PR TITLE
[MultiDB]: apply new APIs in swss-common

### PR DESCRIPTION
**Pull request by dzhangalibaba**
* replacing old APIs with new APIs in swsscommon

Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com

### CODE REVIEW

**Comment by dzhangalibaba** [comment]
@qiluo-msft  FYI

**Comment by qiluo-msft** [comment]
I will approve this after https://github.com/Azure/sonic-swss/pull/1138 passes vs test

**Comment by dzhangalibaba** [comment]
> I will approve this after [Azure/sonic-swss#1138](https://github.com/Azure/sonic-swss/pull/1138) passes vs test

@qiluo-msft https://github.com/Azure/sonic-swss/pull/1138 mergered, we can start on this now

**Comment by qiluo-msft** [comment]
Another comment from @kcudnik 
https://github.com/Azure/sonic-swss-common/pull/318#issuecomment-560337480
> adding "/var/run/redis/sonic-db/database_config.json" to build docker should solve the issue, but also ".at()" should be used on map to get database instances to force those will exists in map, and also throw exception should be added if database config json files not exists

**Comment by dzhangalibaba** [comment]
> Another comment from @kcudnik
> [#318 (comment)](https://github.com/Azure/sonic-swss-common/pull/318#issuecomment-560337480)
> 
> > adding "/var/run/redis/sonic-db/database_config.json" to build docker should solve the issue, but also ".at()" should be used on map to get database instances to force those will exists in map, and also throw exception should be added if database config json files not exists

@qiluo-msft @kcudnik @lguohan 
adding db config file into build docker definitely will solve the issue. Now the question is "do we really want to add it into build docker ?"  What's the difference between build docker having a default db config file at /var/run/redis/sonic-db/ and submodule Makefile coping(mkdir/mkdir) a db config file into /var/run/redis/sonic-db/  at build time ? They all changed the building system. The feedback at sairedis PR suggest NOT copy db config file into build system.  

BTW , I am happy to have a db config by default in build docker, in this way, we don't need to worry for all the submodules who might miss db config file when doing some tests while building time. It will save my life. Can we go ahead with this approach ? Let me know and I can go head to adding it into build docker OR change each individual test case to have this db config file while building.

**Comment by kcudnik** [comment]
seems fine to me, that config needs to be copied to build docker anyway
but you can still address at() methods and file open check if file exists

**Comment by dzhangalibaba** [comment]
> seems fine to me, that config needs to be copied to build docker anyway
> but you can still address at() methods and file open check if file exists

yes. I can start address the at() and file checking first. 

Let's see what's the opinion on adding db config file into build docker from Guohan and Qi. Then we can what's to do on this next.

**Pull request merged**
