### PR TITLE
Add cfgOrch class

### PR DESCRIPTION
**Pull request by JipanYanga**
Signed-off-by: Jipan Yang <jipan.yang@alibaba-inc.com>

jipan@03ed558878e7:/sonic/src/sonic-swss-common/tests$ ./tests --gtest_filter=Cfg*
Running main() from gtest_main.cc
Note: Google Test filter = Cfg*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from CfgOrch
[ RUN      ] CfgOrch.test
Starting cfgOrch testing
- Step 1. Provision TEST_CONFIG_DB
- Step 2. Verify TEST_APP_DB content
- Step 3. Flush TEST_APP_DB
- Step 4. Sync from TEST_CONFIG_DB
- Step 5. Verify TEST_APP_DB content
- Step 6. Clean TEST_CONFIG_DB
- Step 7. Verify TEST_APP_DB content is empty
Done.
[       OK ] CfgOrch.test (11023 ms)
[----------] 1 test from CfgOrch (11023 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (11023 ms total)
[  PASSED  ] 1 test.

### CODE REVIEW

**Comment by JipanYanga** [comment]
Has dependency on https://github.com/Azure/sonic-swss-common/pull/129

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
@stcheng, cfgorch in common? I thought it should be in swss repo.

**Comment by stcheng** [comment]
@lguohan @JipanYanga I agree that this part shall be in the swss repository.

**Comment by JipanYanga** [comment]
@lguohan @stcheng  intfconfd, vlanconfd and possibly other configDB swss daemons may use cfgorch class too.  I'm ok to move cfgorch to swss repository, in that case I'll remove the google unit test script for it.

**Comment by lguohan** [comment]
let's also keep the test in the swss repo.

**Comment by JipanYanga** [comment]
Moving cfgOrch and keeping the google unit test might be a little challenging and will take more time,  googletest framework is created in swss-common.

**Comment by JipanYanga** [comment]
Obsoleted by https://github.com/Azure/sonic-swss/pull/360

**Pull request closed without merging**
