### PR TITLE
[test]: Add MacAddress test

### PR DESCRIPTION
**Pull request by stcheng**
Signed-off-by: Shuotian Cheng <shuche@microsoft.com>

### CODE REVIEW

**Comment by stcheng** [comment]
This test will fail without the fix of adding `const` at the end of the operator.
@kcudnik could you send out your fix on the issue?

**Comment by kcudnik** [comment]
you still need to add bool operator test when mac address is all zeros

**Comment by kcudnik** [comment]
Added fix in #93

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
@kcudnik added.

**Pull request merged**
