### PR TITLE
[Flex Counters] Add a new field for FLEX_COUNTER_TABLE to indicate delay state

### PR DESCRIPTION
**Pull request by shlomibitton**
Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

Introduce a new field for FLEX_COUNTER_TABLE, indicating the current state of flex counters delay.
The indicator will set to 'true' when executing fast-reboot command to ensure no counters are created before enable_counters script is called.

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@shlomibitton is it needed in 202106?
@kculdnik can you please help to merge?

**Comment by shlomibitton** [comment]
> @shlomibitton is it needed in 202106?
> @kculdnik can you please help to merge?

@liat-grozovik Yes it is.

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
