### PR TITLE
Refactor Consumer*Table interface, and optimize popping

### PR DESCRIPTION
**Pull request by qiluo-msft**
Introduced TableConsumable interface and let ProducerTable inherits TableBase interface.

### CODE REVIEW

**Comment by lguohan** [comment]
why 1.0.1 branch, not 1.0.3 branch?

**Comment by qiluo-msft** [comment]
There is no v1.0.3 branch in this repo. I can rename v1.0.1->v1.0.3 after this pull request.
The reason why using this name at the very beginning is because there is only SAI v1.0.1 implementation then.

**Comment by stcheng** [comment]
could you add more information in the commit about the optimization?

**Comment by qiluo-msft** [comment]
That is straightforward. It makes one less empty check for non-empty popping
```
m_buffer.empty()
```

**Comment by lguohan** [comment]
please also add commit description that you have introduced tableconsumable and move producertable to use tablebase directly.

**Comment by lguohan** [comment]
it should be merged into master, right?

**Pull request merged**
