### PR TITLE
[ci]: Fix azure pipeline template branch reference error

### PR DESCRIPTION
**Pull request by xumia**
Fix azure pipeline template branch reference error

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by xumia** [comment]
@kcudnik , after change to use 202012 branch for sonic-swss and sonic-sairedis, the BuildSwss stage is successful, but some tests failed.
The error message is as below, see https://dev.azure.com/mssonic/build/_build/results?buildId=18389&view=logs&j=3f6395b2-1619-5ebe-f305-2aedcf353cb5&t=35460df8-21be-5313-3ee4-50900c6db765
fixture 'dvs_route' not found

Looks like some code not merged to 202012 branch in sonic-swss, do we need to merge https://github.com/Azure/sonic-swss/pull/1644/files to 202012?

**Comment by xumia** [comment]
@lguohan , the sonic-swss-common is referred by multiple azure pipelines, such as sonic-swss, sonic-sairedis, sonic-utilities. It blocks some PRs to complete. Currently, the builds on 202012 branch are failed. I try to fix to change to use 202012 branch, not quite sure the change is ok.

**Comment by kcudnik** [comment]
im not sure about this https://github.com/Azure/sonic-swss/pull/1644/files, maybe it will resolve this

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
>       sonic_slave: sonic-slave-buster

Please use stretch for 201911 C++ libraries.

---
Refers to: azure-pipelines.yml:57 in 8ad8185. [](commit_id = 8ad8185a8524612f38b72ba76cad7db933e3853d, deletion_comment = False)

**Review by qiluo-msft — CHANGES_REQUESTED** [review]
:clock1:

**Comment by qiluo-msft** [comment]
>       sonic_slave: sonic-slave-buster

I just notice the PR is on 202012. So it's good.

---
In reply to: [856504758](https://github.com/Azure/sonic-swss-common/pull/487#issuecomment-856504758) [](http://example.com/codeflow?ancestors=856504758,856504758)

---
Refers to: azure-pipelines.yml:57 in 8ad8185. [](commit_id = 8ad8185a8524612f38b72ba76cad7db933e3853d, deletion_comment = False)

**Pull request merged**
