### PR TITLE
swss-common: add op 'create' case to avoid flush immediately

### PR DESCRIPTION
**Pull request by dzhangalibaba**
* create operation is used when writing routes into ASIC_DB
* operation create is added to make sure 'create' cases are redis pipelined
* with the changes in sairedis and swss, route performance improved by 200~300 routes/sec

  Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com

### CODE REVIEW

**Comment by dzhangalibaba** [comment]
could we make some progress on this, it is pending for a long time. Thanks

**Comment by qiluo-msft** [comment]
Even you tested with writing routes into ASIC_DB, this is not correct in general. For 'create' op, it should flush pipeline including previous ones and creating one. Consider there are many DB connections, queued 'create' will make more dependency waiting.

**Comment by dzhangalibaba** [comment]
1. when producer g_asicState writing ASIC_DB, it is in order and in the queue, so there should not have any dependency among different events. 

2. If you mean returned OID dependency, that is also fine. OID is  done in swss part which has no dependency on ASIC/sairedis.

Let me know if my understanding is wrong. 


> Even you tested with writing routes into ASIC_DB, this is not correct in general. For 'create' op, it should flush pipeline including previous ones and creating one. Consider there are many DB connections, queued 'create' will make more dependency waiting.

**Comment by dzhangalibaba** [comment]
Thanks for review and approve. Could we merge this , then I can use the master branch to do the next development and don't need to patch it locally every time. Thanks.

**Pull request merged**
